name: Build and Deploy SaltRiders Site to GitHub Pages

on:
  push:
    branches:
      - main # Si attiva quando fai push su main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build script
        run: python main.py

      # --- PASSO DI DEBUG AGGIUNTO ---
      # Questo comando ci mostrerà l'esatto contenuto della cartella _site
      # prima che venga fatto il deploy.
      - name: Verify build output
        run: ls -R _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true